version: '3.4'

services:
  playwrightdemo:
    image: playwrightdemo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9090:8080
